package sketch

import (
	"fmt"
	"math"
	"strings"

	"github.com/lestrrat-go/option/v3"
)

// Windowed framing draws the sketch inside a border rectangle with outer
// padding, optionally over a background grid and with a provenance watermark. It
// is additive and gated behind options that default off, so plain SVG output is
// unchanged.

type (
	identFrame       struct{}
	identGrid        struct{}
	identGridSpacing struct{}
	identFramePad    struct{}
	identWatermark   struct{}
)

// WithFrame toggles a "windowed" render: an outer padding is added around the
// drawing and a border rectangle is drawn at that boundary, framing the sketch
// (the sketch's own margin becomes the gap between the frame and the geometry).
func WithFrame(v bool) SVGPNGOption { return svgPNGOption{option.New(identFrame{}, v)} }

// WithGrid toggles a background grid drawn inside the frame, aligned to the
// sketch coordinate origin. It implies a frame. Spacing is chosen automatically
// unless set with [WithGridSpacing].
func WithGrid(v bool) SVGPNGOption { return svgPNGOption{option.New(identGrid{}, v)} }

// WithGridSpacing sets the grid line spacing in sketch units. Zero (the default)
// picks a rounded spacing (1, 2 or 5 × 10ⁿ) giving roughly ten divisions.
func WithGridSpacing(v float64) SVGPNGOption {
	return svgPNGOption{option.New(identGridSpacing{}, v)}
}

// WithFramePadding sets the outer padding between the canvas edge and the frame,
// in sketch units. Zero (the default) scales it to the drawing size.
func WithFramePadding(v float64) SVGPNGOption {
	return svgPNGOption{option.New(identFramePad{}, v)}
}

// WithWatermark sets a provenance string drawn subtly along the frame's bottom
// edge (e.g. "generated by github.com/lestrrat-3d/sketch@<commit>"). Empty (the
// default) draws none. It implies a frame.
func WithWatermark(v string) SVGPNGOption { return svgPNGOption{option.New(identWatermark{}, v)} }

// Windowed-framing colors.
const (
	colorFrameBorder = "#90a4ae" // frame rectangle
	colorGridLine    = "#eceff1" // minor grid line
	colorGridAxis    = "#cfd8dc" // grid line on the x=0 / y=0 axes
	colorWatermark   = "#b0b3b8" // provenance text
)

// framePadding returns the outer padding (canvas edge -> frame) for the current
// options: zero when no framing feature is on (so the layout is unchanged), the
// explicit WithFramePadding value when set, else a size-relative default. w and h
// are the margin-padded content dimensions.
func (s *Sketch) framePadding(cfg svgConfig, w, h float64) float64 {
	if !cfg.frame && !cfg.grid && cfg.watermark == "" {
		return 0
	}
	if cfg.framePad > 0 {
		return cfg.framePad
	}
	pad := 0.05 * math.Hypot(w, h)
	if pad < cfg.margin {
		pad = cfg.margin
	}
	return pad
}

// writeFrameGrid draws the background grid (when enabled) and the frame border.
// The frame interior is the screen rectangle [pad, pad+w] x [pad, pad+h]; b and
// tx/ty relate it back to sketch coordinates so the grid aligns to the origin.
func (s *Sketch) writeFrameGrid(sb *strings.Builder, cfg svgConfig, b bbox, pad, w, h float64, tx, ty func(float64) float64) {
	left, top, right, bottom := pad, pad, pad+w, pad+h

	if cfg.grid {
		step := cfg.gridSpacing
		if step <= 0 {
			step = niceStep(math.Max(b.maxX-b.minX, b.maxY-b.minY))
		}
		if step > 0 {
			// The frame interior maps to sketch x in [b.minX-margin, b.maxX+margin]
			// and y in [b.minY-margin, b.maxY+margin].
			gridLines(sb, step, b.minX-cfg.margin, b.maxX+cfg.margin, cfg.strokeWidth, func(gx float64) (float64, float64, float64, float64) {
				x := tx(gx)
				return x, top, x, bottom
			})
			gridLines(sb, step, b.minY-cfg.margin, b.maxY+cfg.margin, cfg.strokeWidth, func(gy float64) (float64, float64, float64, float64) {
				y := ty(gy)
				return left, y, right, y
			})
		}
	}

	// Frame border on top of the grid.
	fmt.Fprintf(sb,
		`  <rect x="%s" y="%s" width="%s" height="%s" fill="none" stroke="%s" stroke-width="%s"/>`+"\n",
		f(left), f(top), f(w), f(h), colorFrameBorder, f(cfg.strokeWidth))
}

// gridLines emits one grid line per multiple of step in [lo, hi]. line maps a
// sketch coordinate to a screen segment (x1,y1,x2,y2); the coordinate 0 is drawn
// as an emphasized axis line. It caps the count as a runaway guard.
func gridLines(sb *strings.Builder, step, lo, hi, sw float64, line func(float64) (float64, float64, float64, float64)) {
	const maxLines = 1000
	start := math.Ceil(lo/step) * step
	n := 0
	for g := start; g <= hi && n < maxLines; g, n = g+step, n+1 {
		color := colorGridLine
		width := sw * 0.5
		if math.Abs(g) < step*1e-6 { // the x=0 / y=0 axis
			color = colorGridAxis
			width = sw * 0.75
		}
		x1, y1, x2, y2 := line(g)
		fmt.Fprintf(sb,
			`  <line x1="%s" y1="%s" x2="%s" y2="%s" stroke="%s" stroke-width="%s"/>`+"\n",
			f(x1), f(y1), f(x2), f(y2), color, f(width))
	}
}

// writeWatermark draws the provenance string subtly in the outer padding just
// below the frame's bottom-right corner, so it reads as a footer and never
// overlaps the geometry or its dimensions.
func (s *Sketch) writeWatermark(sb *strings.Builder, cfg svgConfig, pad, w, h float64) {
	size := math.Min(0.018*math.Hypot(w, h), pad*0.5)
	if size <= 0 {
		size = 1
	}
	x := pad + w           // right-aligned to the frame's right edge
	y := pad + h + pad*0.6 // in the bottom outer padding, below the frame
	fmt.Fprintf(sb,
		`  <text x="%s" y="%s" font-size="%s" fill="%s" text-anchor="end">%s</text>`+"\n",
		f(x), f(y), f(size), colorWatermark, svgEscape(cfg.watermark))
}

// niceStep returns a rounded step (1, 2 or 5 × 10ⁿ) giving roughly ten divisions
// across span. It is the automatic grid spacing.
func niceStep(span float64) float64 {
	if span <= 0 {
		return 1
	}
	raw := span / 10
	mag := math.Pow(10, math.Floor(math.Log10(raw)))
	switch n := raw / mag; {
	case n < 1.5:
		return mag
	case n < 3:
		return 2 * mag
	case n < 7:
		return 5 * mag
	default:
		return 10 * mag
	}
}
